(if (< (read) (read)) 0 42)
; (let ([i1 (read)])
;   (let ([i2 (read)])
;     (let ([i3 (read)])
;       (let ([i4 (read)])
;         (let ([i5 (read)])
;           (let ([i6 (read)])
;             (let ([i7 (read)])
;               (let ([i8 (read)])
;                 (+ (if (< i1 i2) 0 10)
;                    (+ (if (> i3 i4) 0 10)
;                       (+ (if (<= i5 i6) 10 0)
;                          (if (>= i7 i8) 12 0))))))))))))
