(if (let ((vector-11 (vector #t)))
	  (let ((vector-10 (vector #t)))
		(let ((vector-9 (vector #t)))
		  (let ((vector-8 (vector #t)))
			(let ((vector-7 (vector #t)))
			  (let ((vector-6 (vector #t)))
				(let ((vector-5 (vector #t)))
				  (let ((vector-4 (vector #t)))
					(let ((vector-3 (vector #t)))
					  (let ((vector-2 (vector #t)))
						(let ((vector-1 (vector #t)))
						  (and (vector-ref vector-11 0)
							   (and (vector-ref vector-10 0)
									(and (vector-ref vector-9 0)
										 (and (vector-ref vector-8 0)
											  (and (vector-ref vector-7 0)
												   (and (vector-ref vector-6 0)
														(and (vector-ref vector-5 0)
															 (and (vector-ref vector-4 0)
																  (and (vector-ref vector-3 0)
																	   (and (vector-ref vector-2 0)
																			(and (vector-ref vector-1 0)
																				 #t))))))))))))))))))))))
  42 123)
